import Head from "next/head";
import React, { lazy, Suspense, useCallback, useEffect, useState } from "react";
import { useAppContext } from "~/context/context";
import { throttle } from "lodash";

const Bg = lazy(() => import("~/components/bg"));
const Hero = lazy(() => import("~/components/home/hero/hero"));
const AboutUs = lazy(() => import("~/components/about/aboutUs/aboutUs"));
const Equipment = lazy(() => import("~/components/about/equipment/equipment"));
const MeetOurTeam = lazy(
  () => import("~/components/about/meetOurTeam/meetOurTeam")
);
const Projects = lazy(() => import("~/components/projects/projects/projects"));
const Events = lazy(() => import("~/components/events/events/events"));
const Resources = lazy(
  () => import("~/components/resources/resources/resources")
);
const Footer = lazy(() => import("~/components/footer"));

export default function Home() {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  const {
    scrollPosition,
    heroHeight,
    aboutUsHeight,
    equipmentHeight,
    meetOurTeamHeight,
    projectsHeight,
    eventsHeight,
    resourcesHeight,
    setScrollPosition,
    setHeroHeight,
    setAboutUsHeight,
    setEquipmentHeight,
    setMeetOurTeamHeight,
    setProjectsHeight,
    setEventsHeight,
    setResourcesHeight,
  } = useAppContext();

  const handleSetHeroHeight = useCallback(
    (node: HTMLDivElement) => {
      if (node) {
        setHeroHeight({ height: node?.offsetHeight, pos: 0 });
      }
    },
    [setHeroHeight]
  );
  const handleSetAboutUsHeight = useCallback(
    (node: HTMLDivElement) => {
      if (node) {
        setAboutUsHeight({
          height: node?.offsetHeight,
          pos: heroHeight.height,
        });
      }
    },
    [setAboutUsHeight, heroHeight.height]
  );
  const handleSetEquipmentHeight = useCallback(
    (node: HTMLDivElement) => {
      if (node) {
        setEquipmentHeight({
          height: node?.offsetHeight,
          pos: heroHeight.height + aboutUsHeight.height,
        });
      }
    },
    [setEquipmentHeight, heroHeight.height, aboutUsHeight.height]
  );
  const handleSetMeetOurTeamHeight = useCallback(
    (node: HTMLDivElement) => {
      if (node) {
        setMeetOurTeamHeight({
          height: node?.offsetHeight,
          pos:
            heroHeight.height + aboutUsHeight.height + equipmentHeight.height,
        });
      }
    },
    [
      setMeetOurTeamHeight,
      heroHeight.height,
      aboutUsHeight.height,
      equipmentHeight.height,
    ]
  );
  const handleSetProjectsHeight = useCallback(
    (node: HTMLDivElement) => {
      if (node) {
        setProjectsHeight({
          height: node?.offsetHeight,
          pos:
            heroHeight.height +
            aboutUsHeight.height +
            equipmentHeight.height +
            meetOurTeamHeight.height,
        });
      }
    },
    [
      setProjectsHeight,
      heroHeight.height,
      aboutUsHeight.height,
      equipmentHeight.height,
      meetOurTeamHeight.height,
    ]
  );
  const handleSetEventsHeight = useCallback(
    (node: HTMLDivElement) => {
      if (node) {
        setEventsHeight({
          height: node?.offsetHeight,
          pos:
            heroHeight.height +
            aboutUsHeight.height +
            equipmentHeight.height +
            meetOurTeamHeight.height +
            projectsHeight.height,
        });
      }
    },
    [
      setEventsHeight,
      heroHeight.height,
      aboutUsHeight.height,
      equipmentHeight.height,
      meetOurTeamHeight.height,
      projectsHeight.height,
    ]
  );
  const handleSetResourcesHeight = useCallback(
    (node: HTMLDivElement) => {
      if (node) {
        setResourcesHeight({
          height: node?.offsetHeight,
          pos:
            heroHeight.height +
            aboutUsHeight.height +
            equipmentHeight.height +
            meetOurTeamHeight.height +
            projectsHeight.height +
            eventsHeight.height,
        });
      }
    },
    [
      setResourcesHeight,
      heroHeight.height,
      aboutUsHeight.height,
      equipmentHeight.height,
      meetOurTeamHeight.height,
      projectsHeight.height,
      eventsHeight.height,
    ]
  );

  useEffect(() => {
    const handleScroll = throttle(() => {
      setScrollPosition(window.scrollY + window.innerHeight);
    }, 100);

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, [setScrollPosition]);

  const [showAll, setShowAll] = useState<boolean>(true);
  useEffect(() => {
    setScrollPosition(window.scrollY + window.innerHeight);
    setTimeout(() => {
      setShowAll(false);
    }, 500);
  }, [isClient, setScrollPosition]);

  return (
    <>
      <Head>
        <title>VR Club SJSU</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="relative flex min-h-[100dvh] min-w-full flex-col">
        {isClient && (
          <Suspense>
            <Bg />
            {showAll ||
            (scrollPosition >= heroHeight.pos &&
              scrollPosition - window.innerHeight <
                heroHeight.pos + heroHeight.height) ? (
              <div ref={handleSetHeroHeight}>
                <Hero />
              </div>
            ) : (
              <div style={{ height: `${heroHeight.height}px` }}></div>
            )}
            {showAll ||
            (scrollPosition > aboutUsHeight.pos &&
              scrollPosition - window.innerHeight <
                aboutUsHeight.pos + aboutUsHeight.height) ? (
              <div ref={handleSetAboutUsHeight}>
                <AboutUs />
              </div>
            ) : (
              <div style={{ height: `${aboutUsHeight.height}px` }}></div>
            )}
            {showAll ||
            (scrollPosition > equipmentHeight.pos &&
              scrollPosition - window.innerHeight <
                equipmentHeight.pos + equipmentHeight.height) ? (
              <div ref={handleSetEquipmentHeight}>
                <Equipment />
              </div>
            ) : (
              <div style={{ height: `${equipmentHeight.height}px` }}></div>
            )}
            {showAll ||
            (scrollPosition > meetOurTeamHeight.pos &&
              scrollPosition - window.innerHeight <
                meetOurTeamHeight.pos + meetOurTeamHeight.height) ? (
              <div ref={handleSetMeetOurTeamHeight}>
                <MeetOurTeam />
              </div>
            ) : (
              <div style={{ height: `${meetOurTeamHeight.height}px` }}></div>
            )}
            {showAll ||
            (scrollPosition > projectsHeight.pos &&
              scrollPosition - window.innerHeight <
                projectsHeight.pos + projectsHeight.height) ? (
              <div ref={handleSetProjectsHeight}>
                <Projects />
              </div>
            ) : (
              <div style={{ height: `${projectsHeight.height}px` }}></div>
            )}
            {showAll ||
            (scrollPosition > eventsHeight.pos &&
              scrollPosition - window.innerHeight <
                eventsHeight.pos + eventsHeight.height) ? (
              <div ref={handleSetEventsHeight}>
                <Events />
              </div>
            ) : (
              <div style={{ height: `${eventsHeight.height}px` }}></div>
            )}
            {showAll ||
            (scrollPosition > resourcesHeight.pos &&
              scrollPosition - window.innerHeight <
                resourcesHeight.pos + resourcesHeight.height) ? (
              <div ref={handleSetResourcesHeight}>
                <Resources />
              </div>
            ) : (
              <div style={{ height: `${resourcesHeight.height}px` }}></div>
            )}
            <Footer />
          </Suspense>
        )}
      </main>
    </>
  );
}
